In [14]:
import pandas as pd
import numpy as np
import re

In [15]:
df = pd.read_csv("data/suumo_kawaguchi_pre.csv")

In [16]:
df.isnull().sum()

name         0
price        0
age          0
manage       0
sikikin      0
reikin       0
deposit      0
sikibiki     0
line         0
bus          0
car          0
walk         0
time         0
room         0
R            0
L            0
D            0
S            0
K            0
area         0
direction    0
type         0
address      0
dtype: int64

In [17]:
df

,name,price,age,manage,sikikin,reikin,deposit,sikibiki,line,bus,...,room,R,L,D,S,K,area,direction,type,address
0,プレジュール浦和９１０５４０,10.2,24.0,8000.0,8.0,15.3,0.0,0.0,ＪＲ京浜東北線,0,...,3,0,1,1,0,1,63.10,南,マンション,埼玉県さいたま市南区辻８
1,ＪＲ埼京線 北戸田駅 2階建 築36年,6.7,36.0,3000.0,13.4,0.0,0.0,0.0,ＪＲ京浜東北線,0,...,1,0,1,1,0,1,39.00,西,アパート,埼玉県さいたま市南区辻２
2,ＪＲ埼京線 北戸田駅 3階建 築32年,9.5,32.0,3000.0,9.5,0.0,0.0,0.0,ＪＲ京浜東北線,0,...,3,0,0,1,0,1,55.00,南西,マンション,埼玉県さいたま市南区辻８
3,ＪＲ埼京線 北戸田駅 2階建 築36年,6.7,36.0,3000.0,13.4,0.0,0.0,0.0,ＪＲ京浜東北線,0,...,1,0,1,1,0,1,39.00,西,アパート,埼玉県さいたま市南区辻２
4,レオパレスこま,5.1,16.0,4500.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,0,...,1,0,0,0,0,1,19.87,南東,アパート,埼玉県さいたま市緑区大字大門
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17635,レオパレスアネモス,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,1,...,1,0,0,0,0,1,23.18,なし,マンション,埼玉県川口市東領家３
17636,レオパレスアネモス,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,1,...,1,0,0,0,0,1,23.18,なし,マンション,埼玉県川口市東領家３
17637,レオパレスアネモス,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,1,...,1,0,0,0,0,1,23.18,なし,マンション,埼玉県川口市東領家３
17638,レオパレスアネモス,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,1,...,1,0,0,0,0,1,23.18,なし,マンション,埼玉県川口市東領家３
17639,レオパレスアヴリオ 303号室,5.3,15.0,7000.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,1,...,1,0,0,0,0,1,20.81,なし,マンション,埼玉県川口市東領家３

In [18]:
name = df["name"]

In [19]:
df = df.drop("name",axis=1)

In [20]:
df

,price,age,manage,sikikin,reikin,deposit,sikibiki,line,bus,car,...,room,R,L,D,S,K,area,direction,type,address
0,10.2,24.0,8000.0,8.0,15.3,0.0,0.0,ＪＲ京浜東北線,0,1,...,3,0,1,1,0,1,63.10,南,マンション,埼玉県さいたま市南区辻８
1,6.7,36.0,3000.0,13.4,0.0,0.0,0.0,ＪＲ京浜東北線,0,1,...,1,0,1,1,0,1,39.00,西,アパート,埼玉県さいたま市南区辻２
2,9.5,32.0,3000.0,9.5,0.0,0.0,0.0,ＪＲ京浜東北線,0,1,...,3,0,0,1,0,1,55.00,南西,マンション,埼玉県さいたま市南区辻８
3,6.7,36.0,3000.0,13.4,0.0,0.0,0.0,ＪＲ京浜東北線,0,1,...,1,0,1,1,0,1,39.00,西,アパート,埼玉県さいたま市南区辻２
4,5.1,16.0,4500.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,0,1,...,1,0,0,0,0,1,19.87,南東,アパート,埼玉県さいたま市緑区大字大門
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17635,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,1,0,...,1,0,0,0,0,1,23.18,なし,マンション,埼玉県川口市東領家３
17636,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,1,0,...,1,0,0,0,0,1,23.18,なし,マンション,埼玉県川口市東領家３
17637,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,1,0,...,1,0,0,0,0,1,23.18,なし,マンション,埼玉県川口市東領家３
17638,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,1,0,...,1,0,0,0,0,1,23.18,なし,マンション,埼玉県川口市東領家３
17639,5.3,15.0,7000.0,0.0,0.0,0.0,0.0,ＪＲ京浜東北線,1,0,...,1,0,0,0,0,1,20.81,なし,マンション,埼玉県川口市東領家３

In [21]:
from sklearn.preprocessing import OrdinalEncoder

In [24]:
from sklearn.preprocessing import LabelEncoder
cols = df.columns.tolist()
for col in cols: 
    if df[col].dtypes == object:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        df[col] = df[col].astype(float)

In [25]:
df

,price,age,manage,sikikin,reikin,deposit,sikibiki,line,bus,car,...,room,R,L,D,S,K,area,direction,type,address
0,10.2,24.0,8000.0,8.0,15.3,0.0,0.0,0.0,0,1,...,3,0,1,1,0,1,63.10,4.0,2.0,2.0
1,6.7,36.0,3000.0,13.4,0.0,0.0,0.0,0.0,0,1,...,1,0,1,1,0,1,39.00,8.0,0.0,1.0
2,9.5,32.0,3000.0,9.5,0.0,0.0,0.0,0.0,0,1,...,3,0,0,1,0,1,55.00,6.0,2.0,2.0
3,6.7,36.0,3000.0,13.4,0.0,0.0,0.0,0.0,0,1,...,1,0,1,1,0,1,39.00,8.0,0.0,1.0
4,5.1,16.0,4500.0,0.0,0.0,0.0,0.0,0.0,0,1,...,1,0,0,0,0,1,19.87,5.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17635,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,0.0,1,0,...,1,0,0,0,0,1,23.18,0.0,2.0,137.0
17636,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,0.0,1,0,...,1,0,0,0,0,1,23.18,0.0,2.0,137.0
17637,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,0.0,1,0,...,1,0,0,0,0,1,23.18,0.0,2.0,137.0
17638,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,0.0,1,0,...,1,0,0,0,0,1,23.18,0.0,2.0,137.0
17639,5.3,15.0,7000.0,0.0,0.0,0.0,0.0,0.0,1,0,...,1,0,0,0,0,1,20.81,0.0,2.0,137.0

In [26]:
df_c = pd.concat([name,df],axis=1)

In [27]:
df_c

,name,price,age,manage,sikikin,reikin,deposit,sikibiki,line,bus,...,room,R,L,D,S,K,area,direction,type,address
0,プレジュール浦和９１０５４０,10.2,24.0,8000.0,8.0,15.3,0.0,0.0,0.0,0,...,3,0,1,1,0,1,63.10,4.0,2.0,2.0
1,ＪＲ埼京線 北戸田駅 2階建 築36年,6.7,36.0,3000.0,13.4,0.0,0.0,0.0,0.0,0,...,1,0,1,1,0,1,39.00,8.0,0.0,1.0
2,ＪＲ埼京線 北戸田駅 3階建 築32年,9.5,32.0,3000.0,9.5,0.0,0.0,0.0,0.0,0,...,3,0,0,1,0,1,55.00,6.0,2.0,2.0
3,ＪＲ埼京線 北戸田駅 2階建 築36年,6.7,36.0,3000.0,13.4,0.0,0.0,0.0,0.0,0,...,1,0,1,1,0,1,39.00,8.0,0.0,1.0
4,レオパレスこま,5.1,16.0,4500.0,0.0,0.0,0.0,0.0,0.0,0,...,1,0,0,0,0,1,19.87,5.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17635,レオパレスアネモス,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,0.0,1,...,1,0,0,0,0,1,23.18,0.0,2.0,137.0
17636,レオパレスアネモス,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,0.0,1,...,1,0,0,0,0,1,23.18,0.0,2.0,137.0
17637,レオパレスアネモス,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,0.0,1,...,1,0,0,0,0,1,23.18,0.0,2.0,137.0
17638,レオパレスアネモス,5.6,12.0,7000.0,0.0,0.0,0.0,0.0,0.0,1,...,1,0,0,0,0,1,23.18,0.0,2.0,137.0
17639,レオパレスアヴリオ 303号室,5.3,15.0,7000.0,0.0,0.0,0.0,0.0,0.0,1,...,1,0,0,0,0,1,20.81,0.0,2.0,137.0

In [29]:
df.to_csv('data/df.csv',index=False)